allowBuilds:
  esbuild: true
  msgpackr-extract: true
minimumReleaseAgeExclude:
  - uuid@13.0.1
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - msgpackr-extract
  - oxc-resolver
overrides:
  immutable@>=4.0.0-rc.1 <4.3.8: '5.1.9'
  jsondiffpatch@<0.7.2: '0.7.6'
  lodash@>=4.0.0 <=4.17.22: '4.18.1'
  minimatch@<3.1.3: '10.2.5'
  minimatch@<3.1.4: '10.2.5'
  rollup@>=4.0.0 <4.59.0: '4.62.2'
  seroval@<1.4.1: '1.5.5'
  seroval@<=1.4.0: '1.5.5'
  uuid@>=13.0.0 <13.0.1: 13.0.2
