// Actions
export const ADD_SWITCH = 'ADD_SWITCH'
export const CLEAR_CANDIDATE = 'CLEAR_CANDIDATE'
export const CLEAR_LOG = 'CLEAR_LOG'
export const FLIP_ALL_CHESS = 'FLIP_ALL_CHESS'
export const INCREMENT_HISTORY = 'INCREMENT_HISTORY'
export const PLACE_CANDIDATE = 'PLACE_CANDIDATE'
export const PLACE_CHESS = 'PLACE_CHESS'
export const PUSH_LOG = 'PUSH_LOG'
export const REBOOT = 'REBOOT'
export const RESET = 'RESET'
export const RESET_BOARD = 'RESET_BOARD'
export const RESET_SWITCH = 'RESET_SWITCH'
export const RESTORE_STEP = 'RESTORE_STEP'
export const SAVE_STEP = 'SAVE_STEP'
export const SET_AI = 'SET_AI'
export const SET_CANDIDATE = 'SET_CANDIDATE'
export const SET_MESSAGE = 'SET_MESSAGE'
export const SET_OVERLAY = 'SET_OVERLAY'
export const SET_PLAYER = 'SET_PLAYER'
export const SET_RETRACT_STEP = 'SET_RETRACT_STEP'
export const SET_STATE = 'SET_STATE'
export const SET_VERSION = 'SET_VERSION'
export const SWITCH_PLAYER = 'SWITCH_PLAYER'
export const USER_PLACE_CHESS = 'USER_PLACE_CHESS'

// Chess
export const WHITE = 'W'
export const BLACK = 'B'
export const WHITE_CANDIDATE = 'WC'
export const BLACK_CANDIDATE = 'BC'

// State
export const IDLE = 'IDLE'
export const PLAYING = 'PLAYING'
export const ENDED = 'ENDED'
