name: Test
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - name: Setup pnpm
        uses: pnpm/action-setup@v6.0.9
      - uses: actions/setup-node@v7.0.0
        with:
          node-version: 24.18.0
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm dlx playwright install chromium --with-deps
      - run: pnpm test
