name: Test
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: nubjs/setup-nub@v0
      - run: nub install
      - run: nub dlx playwright install chromium --with-deps
      - run: nub run test
